// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP9EJuoyoeuxmLy2IXeK6UQEELmHy2nv8',
    appId: '1:598655007949:web:89310e11c6c68f82f03d84',
    messagingSenderId: '598655007949',
    projectId: 'handygo2',
    authDomain: 'handygo2.firebaseapp.com',
    storageBucket: 'handygo2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcYVt1tuDWYnO8M8PSW_jpD-rxy1cA-UU',
    appId: '1:598655007949:android:b717220afccf40caf03d84',
    messagingSenderId: '598655007949',
    projectId: 'handygo2',
    storageBucket: 'handygo2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSX2JVNKBED6Ff6tIgKIuMzcZec_eDMUQ',
    appId: '1:598655007949:ios:41f8965354aff068f03d84',
    messagingSenderId: '598655007949',
    projectId: 'handygo2',
    storageBucket: 'handygo2.firebasestorage.app',
    iosBundleId: 'com.example.handygo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSX2JVNKBED6Ff6tIgKIuMzcZec_eDMUQ',
    appId: '1:598655007949:ios:41f8965354aff068f03d84',
    messagingSenderId: '598655007949',
    projectId: 'handygo2',
    storageBucket: 'handygo2.firebasestorage.app',
    iosBundleId: 'com.example.handygo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP9EJuoyoeuxmLy2IXeK6UQEELmHy2nv8',
    appId: '1:598655007949:web:181a5daf7613b446f03d84',
    messagingSenderId: '598655007949',
    projectId: 'handygo2',
    authDomain: 'handygo2.firebaseapp.com',
    storageBucket: 'handygo2.firebasestorage.app',
  );
}
